name: data
on:
  schedule:
    - cron: "25 1 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/update.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |-
          python fixmystreet.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
      - name: Deploy Datasette using Vercel
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: |-
          datasette publish vercel fixmystreet.db --install=datasette-vega \
            --token $NOW_TOKEN \
            --project lewisham-fixmystreet-history

